server.port=8080

postgresql://kevin:NbPhgDXuzjEyEnPBBXgTodOq5XMUJ9bq@dpg-d9hdtnbtqb8s739dehu0-a/platzi_play_db_rhih
spring.datasource.url=jdbc:postgresql://dpg-d9hdtnbtqb8s739dehu0-a:5432/platzi_play_db_rhih
spring.datasource.username=kevin
spring.datasource.password=NbPhgDXuzjEyEnPBBXgTodOq5XMUJ9bq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#postgresql://@dpg-d9hdtnbtqb8s739dehu0-a.oregon-postgres.render.com/platzi_play_db_rhih


#LaungChan4j
langchain4j.open-ai.chat-model.api-key=demo
